/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;

/**
 *
 * @author Siddhartha
 */
public class Mess extends javax.swing.JFrame {

    /**
     * Creates new form Mess
     */
    public Mess() {
        initComponents();
        MessTable.setRowHeight(0, 40);
        MessTable.setRowHeight(1, 40);
        MessTable.setRowHeight(2, 40);
        MessTable.setRowHeight(3, 40);
        MessTable.setRowHeight(4, 40);
        MessTable.setRowHeight(5, 40);
        MessTable.setRowHeight(6, 40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MessTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(935, 439));
        getContentPane().setLayout(null);

        MessTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Monday", "Chole Bhatura", "Chapati, Beetroot palya, Rice, Dal", "Dahi Vada", "Chapati, Dum Aloo"},
                {"Tuesday", "Set Dosa", "Chapati, Bhindi, Rice, Dal", "Mangalore Baiji", "Veg Noodles, Chapati, Hesarukalu palya, Rice, Dal"},
                {"Wednesday", "Burger", "Poori, Veg Kurma", "Plain Cake", "Rumali Roti, Chicken Kebab, Dal, Rice"},
                {"Thursday", "Masala Dosa", "Chapati, ThondeKaayi", "Panipuri", "Coconut Rice, Chapati, Malai Kofta"},
                {"Friday", "Aloo Parata", "Chapati, Channa Masala, Rice, Dal", "Finger Chips", "Egg/Veg Biryani"},
                {"Saturday", "Idly, Vada", "Chapati, Egg Masala", "", null},
                {"Sunday", "Full fry, Egg fry, Bread, Butter", "Babycorn Manchurian, Chapati, Rice Dal", "Veg and Egg Puff", "Laccha Paratha, Chicken Manchurian, Butter Roti"}
            },
            new String [] {
                "Day", "Breakfast", "Lunch", "Snacks", "Dinner"
            }
        ));
        MessTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(MessTable);
        MessTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 920, 310);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 340, 59, 25);

        jButton2.setText("Sign Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 340, 90, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/8BjiwmNT.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -30, 720, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/8BjiwmNT.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 0, 230, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loginpage o = new loginpage();
        o.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        page o2 = new page();
        o2.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MessTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
